a = int(input('What is your current age?: '))
months_left_is = ((90-a)* 12.008)
weeks_left_is = ((90 - a) * 52.1428)
days_left_is = ((90-a)* 365.3)
print(f'You have {round(days_left_is)} days, {round(weeks_left_is)} weeks and {round(months_left_is)} months to live.')
